"""empty message

Revision ID: 65901becab9e
Revises: e66f30a8db2e
Create Date: 2023-07-31 12:21:05.109457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65901becab9e'
down_revision = 'e66f30a8db2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('want_to_visit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('want_to_visit')
        batch_op.drop_column('visited')

    # ### end Alembic commands ###
