"""empty message

Revision ID: e66f30a8db2e
Revises: 6eb1acc12be1
Create Date: 2023-07-31 11:06:46.769412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66f30a8db2e'
down_revision = '6eb1acc12be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('List of destinations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('List of destinations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"List of destinations_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='List of destinations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='List of destinations_pkey')
    )
    op.drop_table('Comment')
    op.drop_table('destinations')
    # ### end Alembic commands ###
